models/visits.py
"""
This file have the model
for the visits in the database.
"""

from utils.db import db

class NumberValueInvalid(TypeError):
  """
  Class for create execption
  in case the number passed for parameter not is valid.
  """
  pass


class Visits(db.Model):
  """
  Model for the visits:

  number:str The number for the visit created

  """

  # creating columns
  number = db.Column(db.Integer, primary_key = True)

  def __init__(self, number:int) -> None:
    if type(number) not in [int]:
      raise NumberValueInvalid('The value for the database is invalid')

    # values
    self.number = number

app.py
"""
This file have some
configurations and initials values
for the server.

For execute the server, execute
the file index.py

"""

from flask import Flask
from routes.calendar_routes import calendar
from flask_sqlalchemy import SQLAlchemy
from config import SQLITE_CONNECTION

# creating
app = Flask(__name__)

# settins
app.config['SQLALCHEMY_DATABASE_URI'] = SQLITE_CONNECTION
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

# database
SQLAlchemy(app)

# getting routes
app.register_blueprint(calendar)

routes/calendar_routes.py
"""
This file have
the routes to visit for the website.
"""

from flask import Blueprint, render_template
from utils.db import db
from models.visits import Visits
from utils.counter import get_counter

# routes
calendar = Blueprint('calendar', __name__)

# counter for the visits
counter = get_counter()


def add_visit(counter:int):
  """
  Add the visit passed for parameter
  """

  visits = Visits.query.all()
  visit = Visits(int(counter))
  db.session.add(visit)
  db.session.commit()


@calendar.route('/')
@calendar.route('/home')
def home():
  """
  Initial route for the server.
  """

  global counter
  add_visit(counter)
  counter += 1 # adding the visits
  return render_template('index.html')

@calendar.route('/download')
def get_download():
  """
  Route for render the page of download.
  """

  global counter
  add_visit(counter) # adding visit
  counter += 1

  return render_template('get-download.html')

templates/get-download.html
<!-- PAGE FOR DOWNLOAD -->
{% extends 'layout.html' %}

{% block body %}
<!-- CUSTOM STYLE -->
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/download.css') }}">

<h1 class="text-white text-start">Download</h1>
<hr class="text-white mb-5">

<!-- DOWNLOADS VIEW -->
<section class="downloads-view">

  <div class="clearfix p-3 download">
    <div class="float-start">
      <h2 class="text-white">GNU/Linux or Mac.</h2>
      <p>
        Linux and Mac <strong>64 bits.</strong>
      </p>
    </div>

    <a class="btn btn-primary float-end mt-3 get-button" href="{{ url_for('static', filename = 'files/calendar') }}" download="calendar">
      Get
    </a>

  </div>
</section>

{% endblock %}

templates/index.html
<!-- PRINCIPAL PAGE -->
{% extends 'layout.html' %}

{% block body %}

<h1 class="display-4 text-white">
  What is?
</h1>

<p class="text-justify description mt-4 mb-5 p-3">
  Calendar Terminal App, is a application for watch calendars of whatever year or month from
  the terminal or console.<br>Current Version is <strong>1.0</strong>, only for <strong>Linux and Mac.</strong> But comming soon for <strong>Windows.</strong>
</p>

<img src="{{ url_for('static', filename = 'img/screenshot.png') }}" alt="screenshot" id="screenshot">

<h1 class="display-4 text-white my-5">
  Use.
</h1>

<p class="my-5 use-info">
  Download the program in the section of <a class="btn btn-success mx-2" href="{{ url_for('calendar.get_download') }}" id="download-button">
    download
  </a>
  After you can use the program of this form.
</p>

<!-- USE VIEW -->
<ol class="use-view">
  <li>
    <section class="use-section">
      <h2 class="text-white mb-2">
        GNU/Linux and Mac OS.
      </h2>

      <p class="text-dark mb-4">
        When you have the program downloaded, you can execute
        for see alls the help and use. <br>
        Also you can move the program to <strong>/usr/bin</strong>. For execute without the <strong>./</strong>
      </p>
      <code class="code-example">
        <span class="text-center">./calendar -h</span>
      </code>

    </section>

    <!-- MORE EXAMPLES -->
    <section class="my-5 more-examples">
      <p class="text-dark mb-4">For see a year or month.</p>
      <code class="code-example">
        ./calendar -y 2015 -m 12
      </code>
      <code class="code-example">
        ./calendar --year 2020 <br> --month 3
      </code>

    </section>

    <section class="mb-4 more-examples">
      <p class="text-dark mb-4">If you can get the year current and alls the months. <br> Execute easily.</p>
      <code class="code-example">
        ./calendar
      </code>
    </section>

  </li>

</ol>

{% endblock %}

templates/info.html
{% extends 'layout.html' %}

{% block body %}
<p class="text-center my-5 lead text-white">You pressed the button!</p>

<a class="btn btn-success w-100" href="{{ url_for('home') }}">Back</a>
{% endblock  %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Calendar Terminal App</title>
  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/bootstrap.min.css') }}">
  <!-- CUSTOM STYLE -->
  <link rel="stylesheet" href="{{ url_for('static', filename = 'css/main.css') }}">
</head>
<body>

  <header>
    {% include 'partials/_nav.html' %}
  </header>

  <!-- CONTAINER -->
  <div class="container" id="principal-container">
    {% block body %}
    {% endblock %}
  </div>

  {% include 'partials/_footer.html' %}

  <!-- SCRIPTS -->
  <script src="{{ url_for('static', filename = 'js/bootstrap.bundle.min.js') }}"></script>
  
</body>
</html>

templates/partials/_footer.html
<!-- FOOTER TO USE -->
<footer class="bg-dark p-1 footer">
  <p class="text-white text-center my-3">2022.</p>

  <p class="text-white text-center mb-4">Website made for <span id="my-name">Daniel Yanes.</span></p>

  <div class="links">
    <a class="btn btn-primary my-3 text-center d-block" href="https://github.com/EduardYan/" target="_blank">
      My Github
    </a>
    <a class="btn btn-warning my-3 text-center d-block" href="mailto:eduarygp@gmail.com">
      Contact Me
    </a>
  </div>

</footer>

templates/partials/_nav.html
<!-- NAV TO USE -->
<!-- STYLES FOR NAV -->
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/nav.css') }}">

<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand navbar-title" href="{{ url_for('calendar.home') }}">
      Calendar Terminal App
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('calendar.get_download') }}">
            Download
          </a>
        </li>
      </ul>

    </div>
  </div>

</nav>